//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Самостоятельня_работа_на_уроке
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Компьтерные_x0020_заказыContainer : DbContext
    {
        public Компьтерные_x0020_заказыContainer()
            : base("name=Компьтерные_x0020_заказыContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arvutitellemused> ArvutitellemusedSet { get; set; }
        public virtual DbSet<Whopacked> WhopackedSet { get; set; }
    }
}
